monitor_queue_sizes:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args: [ queue_sizes, ignore_and_log_errors ]
  description: "Send queue sizes to Librato"
monitor_failed:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args: [ failed, ignore_and_log_errors ]
  description: "Send failed job counts to Librato"
monitor_stale_workers:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args: [ stale_workers, ignore_and_log_errors ]
  description: "Send stale worker counts to Librato"
monitor_failed_by_class:
  cron: "* * * * * America/New_York"
  class: "MonitorJob"
  queue: monitor
  args: [ failed_by_class, ignore_and_log_errors ]
  description: "Send failed job counts by class to Librato"
kill_stale_workers:
  # Every hour on the 8's
  cron: "8 * * * * America/New_York"
  class: "Resqutils::StaleWorkersKiller"
  queue: worker_killer_job
  description: "Kills any stale workers"
